### ISSUE TITLE
pip install yara_x==0.5.0 not working for python

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [VirusTotal/yara-x#149]
pip install yara_x==0.5.0
```
DEPRECATION: Loading egg at c:\users\victim\appdata\local\programs\python\python312\lib\site-packages\ssdeep_windows_32_64-0.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting yara_x==0.5.0
  Using cached yara_x-0.5.0-cp38-abi3-win_amd64.whl.metadata (1.8 kB)
Using cached yara_x-0.5.0-cp38-abi3-win_amd64.whl (5.6 MB)
Installing collected packages: yara_x
  Attempting uninstall: yara_x
    Found existing installation: yara-x 0.4.0
    Uninstalling yara-x-0.4.0:
      Successfully uninstalled yara-x-0.4.0
  Rolling back uninstall of yara-x
  Moving to c:\users\victim\appdata\local\programs\python\python312\lib\site-packages\yara_x-0.4.0.dist-info\
   from C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\~ara_x-0.4.0.dist-info
  Moving to c:\users\victim\appdata\local\programs\python\python312\lib\site-packages\yara_x\
   from C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\~ara_x
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\commands\install.py", line 455, in run
    installed = install_given_reqs(
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\req\__init__.py", line 70, in install_given_reqs
    requirement.install(
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\req\req_install.py", line 851, in install
    install_wheel(
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 726, in install_wheel
    _install_wheel(
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 584, in _install_wheel
    file.save()
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 382, in save
    shutil.copyfileobj(f, dest)
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 203, in copyfileobj
    while buf := fsrc_read(length):
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 989, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1079, in _read1
    self._update_crc(data)
  File "C:\Users\victim\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1007, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'yara_x/yara_x.pyd'
```

**Comment by plusvic** [comment]
The file uploaded to PyPI for Python 3.8 and Windows got corrupt. I'll try to upload it again.

**Comment by plusvic** [comment]
Unfortunately PyPI doesn't allow to upload the same file again, I'm forced to bump the version number even though there's no real change. But uploading a 0.5.1 to PyPI without creating a whole 0.5.1 release would be confusing. So, for the time being I'll wait until the next release. The only corrupted package seems to be the one for Python 3.8 and Windows.

This is not the first time I see this problem, the Github workflow that generates the Python wheel files runs ok, and I can download the correct packages from Github, but they get corrupted in the process of uploading them to PyPI.

**Comment by HydraDragonAntivirus** [comment]
Ok now it was fixed.
